-- INSERT INTO tb_personagem(nome, prob_construir, prob_coletar, prob_mineirar, vitorias, derrotas)
-- VALUES
-- ('Steve', '0.33' , '0.33', '0.33', '0', '0'),
-- ('Alex', '0.30', '0.30', '0.40', '0', '0');

-- CREATE TABLE tb_personagem(
--     cod_personagem SERIAL PRIMARY KEY,
--     nome VARCHAR(200) NOT NULL,
--     prob_construir DECIMAL(2, 2),
--     prob_coletar DECIMAL(2, 2),
--     prob_mineirar DECIMAL(2, 2),
--     vitorias INT,
--     derrotas INT
-- );
